### ISSUE TITLE
[ARCHETYPE-202] Can't download archetype-catalog.xml via proxy connection

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#315]
**[Leonid E. Egorov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lswa)** opened **[ARCHETYPE-202](https://issues.apache.org/jira/browse/ARCHETYPE-202?redirect=false)** and commented

According "Your first Cocoon application using Maven 2" (http://cocoon.apache.org/2.2/1159_1_1.html) after execution:

```
mvn archetype:generate -DarchetypeCatalog=http://cocoon.apache.org user should enter into dialog about selecting archetype but nothing happen. Error message:
D:\MySolutions\java\cocoon\demo>mvn archetype:generate -DarchetypeCatalog=http://cocoon.apache.org
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'archetype'.
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO]    task-segment: [archetype:generate] (aggregator-style)
[INFO] ------------------------------------------------------------------------
[INFO] Preparing archetype:generate
[INFO] No goals needed for project - skipping
[INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[INFO] Setting property: velocimacro.messages.on => 'false'.
[INFO] Setting property: resource.loader => 'classpath'.
[INFO] Setting property: resource.manager.logwhenfound => 'false'.
[INFO] [archetype:generate]
[INFO] Generating project in Interactive mode
[WARNING] Error reading archetype catalog http://cocoon.apache.org
org.apache.maven.wagon.TransferFailedException: Error transferring file
        at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:104)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:68)
        at org.apache.maven.archetype.source.RemoteCatalogArchetypeDataSource.getArchetypeCatalog(RemoteCatalogArchetypeDataSource.java:74)
        at org.apache.maven.archetype.DefaultArchetype.getRemoteCatalog(DefaultArchetype.java:203)
        at org.apache.maven.archetype.ui.DefaultArchetypeSelector.getArchetypesByCatalog(DefaultArchetypeSelector.java:249)
        at org.apache.maven.archetype.ui.DefaultArchetypeSelector.selectArchetype(DefaultArchetypeSelector.java:74)
        at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execute(CreateProjectFromArchetypeMojo.java:180)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:227)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: java.net.NoRouteToHostException: No route to host: connect
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
        at java.net.Socket.connect(Socket.java:519)
        at java.net.Socket.connect(Socket.java:469)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:157)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:394)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:529)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:233)
        at sun.net.www.http.HttpClient.New(HttpClient.java:306)
        at sun.net.www.http.HttpClient.New(HttpClient.java:323)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:788)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:729)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:654)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:977)
        at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:83)
        ... 24 more
[INFO] No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)
Choose archetype:
Choose a number: : Choose archetype:
Choose a number: : &#1047;&#1072;&#1074;&#1077;&#1088;&#1096;&#1080;&#1090;&#1100; &#1074;&#1099;&#1087;&#1086;&#1083;&#1085;&#1077;&#1085;&#1080;&#1077; &#1087;&#1072;&#1082;&#1077;&#1090;&#1085;&#1086;&#1075;&#1086; &#1092;&#1072;&#1081;&#1083;&#1072; [Y(&#1076;&#1072;)/N(&#1085;&#1077;&#1090;)]? ^C

D:\MySolutions\java\cocoon\demo>mvn --version
Maven version: 2.0.9
Java version: 1.6.0_06
OS name: "windows xp" version: "5.1" arch: "x86" Family: "windows"

D:\MySolutions\java\cocoon\demo>
```

It's look like no proxy using for downloading catalog file from cocoon site.

---

**Affects:** 2.0-alpha-2

**Attachments:**
- [ARCHETYPE-202-archetype-common.patch](https://issues.apache.org/jira/secure/attachment/12713824/ARCHETYPE-202-archetype-common.patch) (_2.88 kB_)

14 votes, 12 watchers

**Comment by jira-importer** [comment]
**[Ronald Kieft](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rekieft)** commented

I'm also connected to the internet via a proxy and I'm facing the same problem.

I'm using maven-2.1.0 and version 2.0-alpha-4 of the maven-archetype-plugin.

Maybe increase the priority?

**Comment by jira-importer** [comment]
**[Heath Raftery](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hraftery)** commented

This is a show stopper for those of us behind a proxy. Maven works fine through the proxy (as configured in ~/.m2/settings.xml), so perhaps archetype should pick up those settings. Is there any workaround?

**Comment by jira-importer** [comment]
**[Heath Raftery](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hraftery)** commented

Workaround:

1. Download the archetype-catalog.xml file manually and place it in `~/.m2/`
2. Use `mvn archetype:generate -DarchetypeCatalog=local` instead.
3. Magic.

**Comment by jira-importer** [comment]
**[Leonid E. Egorov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lswa)** commented

Another way is manually select desired archetype by simply call: mvn archetype:generate (http://www.nabble.com/Error-reading-archetype-catalog-http%3A--cocoon.apache.org-td19281789.html#a19301611) from Raphaël. But this is a some kind of tricks no standard way. Now I check Maven-2.2.0 and get the same result...

**Comment by jira-importer** [comment]
**[Bruce Albrecht](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bgalbrecht)** commented

We have an internal repository that requires authentication (thank you, paranoid security drones), and it fails to retrieve archetype-catalog.xml also.

**Comment by jira-importer** [comment]
**[Yohan Yudanara](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yohan_y)** commented

How to increase the fixing priority of this bug ?
It seems that this bug have been abandoned for a long time.
I'm using maven-2.1.0

**Comment by jira-importer** [comment]
**[Marco Rico-Gomez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mrico)** commented

I think the problem is located in the class RemoteCatalogArchetypeDataSource.

It uses Wagon to download the archetype-catalog.xml file, but doesn't call the connect method with an (possible) AuthenticationInfo and ProxyInfo object.

With the attached patch I was able to download the file from behind a http proxy configured in the settings.xml

**Comment by jira-importer** [comment]
**[Sébastien Deleuze](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bouiaw)** commented

Seriously, this make Maven archetype unusable in all companies !!! This bug is open since 2008, and has minor priority.
Please raise the priority of this bug. I hope Herve or any one else will find the time to fix it.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

thanks for the patch: applied in r952423

don't forget to use a repository manager in Corporate environment

**Comment by jira-importer** [comment]
**[Clemens Benden](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cbenden)** commented

$ ..\..\maven\bin\mvn --version
Apache Maven 2.2.1 (r801777; 2009-08-06 21:16:01+0200)
Java version: 1.6.0_21
Java home: C:\Program Files\Java\jdk1.6.0_21\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows xp" version: "5.1" arch: "x86" Family: "windows"

This problem still exists.

The workaround from Heath Raftery still works:

1. download archetype-catalog.xml from http://repo1.maven.org/maven2 with a webbrowser (save link as...)
2. move file to your local .m2 folder
3. Use mvn archetype:generate -DarchetypeCatalog=local instead.

*** 

*** CAN ANYBODY PLEASE FIX THIS?

***

Please make the workaround more visible in the meantime.

Google tags:
Unable to update index for central
Updating index central
Unable to download Repository
maven bug not fixed
maven proxy firewall
maven proxy firewall workaround
maven proxy firewall corporate

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

I don't understand: did you try a 2.0-alpha-6-SNAPSHOT after the fix in r952423 and found that it doesn't work?
or did you try without precise version information, then got a release that we know has the bug (no surprise)?

In fact, I applied the patch since it looked consistent but didn't really **test** it (and didn't write an integration test): having some feedback confirming the new snapshot is ok would help

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

real user test is ok: http://maven.40175.n5.nabble.com/Archetype-plugin-2-0-alpha-6-release-tp2807769p2837741.html

thanks to the reporter

**Comment by jira-importer** [comment]
**[charles](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chrc)** commented

> ??Herve Boutemy said :??
> thanks for the patch: applied in r952423
> don't forget to use a repository manager in Corporate environment

I need this release IN M2ECLIPSE plugin to work well.
How can I obtain this ?

Thx a lot.

Chris

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

m2e is done at Eclipse now: see http://www.eclipse.org/m2e/ to use their issue tracking
