### ISSUE TITLE
[ARCHETYPE-304] problem with "mvn archetype:generate" for ear-jee5 (168)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#331]
**[vincent laugier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vlaugier)** opened **[ARCHETYPE-304](https://issues.apache.org/jira/browse/ARCHETYPE-304?redirect=false)** and commented

Hello,

when calling 'mvn archetype:generate'

```
Choose a number: 58: 168
Choose version:
1: 1.0
2: 1.0.1
Choose a number: : 1
[ERROR] Cannot parse archetype descriptor
org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unknown attribute 'id' for tag 'archetype-descriptor' (position: START_TAG seen ...escriptor id="ear-jee5" partial="false" name="JEE5 EAR archetype">... @2:79)
        at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Reader.checkUnknownAttribute(ArchetypeDescriptorXpp3Reader.java:99)
        at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Reader.parseArchetypeDescriptor(ArchetypeDescriptorXpp3Reader.java:579)
        at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Reader.read(ArchetypeDescriptorXpp3Reader.java:1212)
        at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Reader.read(ArchetypeDescriptorXpp3Reader.java:1141)
        at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.loadFileSetArchetypeDescriptor(DefaultArchetypeArtifactManager.java:477)
        at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.isFileSetArchetype(DefaultArchetypeArtifactManager.java:455)
        at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.isFileSetArchetype(DefaultArchetypeArtifactManager.java:187)
        at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.isFileSetArchetype(DefaultArchetypeArtifactManager.java:215)
        at org.apache.maven.archetype.ui.DefaultArchetypeGenerationConfigurator.configureArchetype(DefaultArchetypeGenerationConfigurator.java:141)
        at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execute(CreateProjectFromArchetypeMojo.java:188)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:453)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:559)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:513)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:483)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:331)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:228)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:301)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] The defined artifact is not an archetype
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25 minutes 57 seconds
[INFO] Finished at: Wed May 05 18:05:10 CEST 2010
[INFO] Final Memory: 12M/79M
[INFO] ------------------------------------------------------------------------
```

---

**Issue Links:**
- [ARCHETYPE-333](https://issues.apache.org/jira/browse/ARCHETYPE-333) Errors creating project from previously accepted archetype
 (_**"is duplicated by"**_)

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Valery Khromov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vkhromov)** commented

Same for ejb-javaee6:

C:\>mvn archetype:generate

Choose a number: 58: 170
Choose version:
1: 1.0
2: 1.0.1
3: 1.0.2
Choose a number: : 3

[ERROR] Cannot parse archetype descriptor
org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unknown attribute 'id'
for tag 'archetype-descriptor' (position: START_TAG seen ...id="ejb-javaee6" pa
rtial="false" name="JavaEE6 ejb jar archetype">... `@2`:89)
at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Re
ader.checkUnknownAttribute(ArchetypeDescriptorXpp3Reader.java:99)
at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Re
ader.parseArchetypeDescriptor(ArchetypeDescriptorXpp3Reader.java:579)
at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Re
ader.read(ArchetypeDescriptorXpp3Reader.java:1212)
at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Re
ader.read(ArchetypeDescriptorXpp3Reader.java:1141)
at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.loa
dFileSetArchetypeDescriptor(DefaultArchetypeArtifactManager.java:477)
at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.isF
ileSetArchetype(DefaultArchetypeArtifactManager.java:455)
at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.isF
ileSetArchetype(DefaultArchetypeArtifactManager.java:187)
at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.isF
ileSetArchetype(DefaultArchetypeArtifactManager.java:215)
at org.apache.maven.archetype.ui.DefaultArchetypeGenerationConfigurator.
configureArchetype(DefaultArchetypeGenerationConfigurator.java:141)
at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execu
te(CreateProjectFromArchetypeMojo.java:188)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:694)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandalone
Goal(DefaultLifecycleExecutor.java:569)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:284)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:6
0)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

C:\>mvn --version
Apache Maven 2.2.1 (r801777; 2009-08-06 23:16:01+0400)
Java version: 1.6.0_20
Java home: C:\Progra~1\Java\jdk1.6.0_20\jre
Default locale: ru_RU, platform encoding: Cp1251
OS name: "windows 7" version: "6.1" arch: "amd64" Family: "windows"

**Comment by jira-importer** [comment]
**[Helge Tesgaard](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=helgetuser)** commented

When you execute:
mvn --debug archetype:generate -DgroupId=\<some groupId> -DartifactId=\<some artifactId>

you see:
[DEBUG] Searching for META-INF/archetype.xml inside C:\dokumenter\.m2\repository\org\codehaus\mojo\archetypes\ear-jee5\1.0\ear-jee5-1.0.jar
[DEBUG]   - META-INF/
[DEBUG]   - META-INF/MANIFEST.MF
[DEBUG]   - archetype-resources/
[DEBUG]   - archetype-resources/src/
[DEBUG]   - archetype-resources/src/main/
[DEBUG]   - archetype-resources/src/main/application/
[DEBUG]   - archetype-resources/src/main/application/META-INF/
[DEBUG]   - META-INF/maven/
[DEBUG]   - archetype-resources/src/main/application/META-INF/MANIFEST.MF
[DEBUG]   - archetype-resources/pom.xml
[DEBUG]   - META-INF/maven/archetype-metadata.xml
[DEBUG]   - META-INF/maven/org.codehaus.mojo.archetypes/
[DEBUG]   - META-INF/maven/org.codehaus.mojo.archetypes/ear-jee5/
[DEBUG]   - META-INF/maven/org.codehaus.mojo.archetypes/ear-jee5/pom.xml
[DEBUG]   - META-INF/maven/org.codehaus.mojo.archetypes/ear-jee5/pom.properties
[DEBUG] No found META-INF/archetype.xml retrying with windows path separator.

This seams to indicate indicates that "META-INF/archetype.xml" is now moved to "META-INF/maven/archetype-metadata.xml"

Environment:
C:\source\svn\SingleSignOn>mvn -version
Apache Maven 2.2.1 (r801777; 2009-08-06 21:16:01+0200)
Java version: 1.6.0_14
Java home: C:\dokumenter\java\jdk1.6.0_14\jre
Default locale: da_DK, platform encoding: Cp1252
OS name: "windows xp" version: "5.1" arch: "x86" Family: "windows"

**Comment by jira-importer** [comment]
**[Pascal Thivent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pthivent)** commented

Same problem with webapp-jee5

```
  
$ mvn archetype:generate
...
Choose a number: 63: 182
Choose version: 
1: 1.0
2: 1.0.1
Choose a number: : 1
      
[ERROR] Cannot parse archetype descriptor
org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unknown attribute 'id' for tag 'archetype-descriptor' (position: START_TAG seen ...ebapp-jee5" partial="false" name="JEE5 web application archetype">... @2:94) 
	at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Reader.checkUnknownAttribute(ArchetypeDescriptorXpp3Reader.java:99)
	at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Reader.parseArchetypeDescriptor(ArchetypeDescriptorXpp3Reader.java:579)
	at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Reader.read(ArchetypeDescriptorXpp3Reader.java:1212)
	at org.apache.maven.archetype.metadata.io.xpp3.ArchetypeDescriptorXpp3Reader.read(ArchetypeDescriptorXpp3Reader.java:1141)
	at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.loadFileSetArchetypeDescriptor(DefaultArchetypeArtifactManager.java:477)
	at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.isFileSetArchetype(DefaultArchetypeArtifactManager.java:455)
	at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.isFileSetArchetype(DefaultArchetypeArtifactManager.java:187)
	at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.isFileSetArchetype(DefaultArchetypeArtifactManager.java:215)
	at org.apache.maven.archetype.ui.DefaultArchetypeGenerationConfigurator.configureArchetype(DefaultArchetypeGenerationConfigurator.java:141)
	at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execute(CreateProjectFromArchetypeMojo.java:188)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

Environment:

```
 
$ mvn --version
Apache Maven 2.2.1 (r801777; 2009-08-06 21:16:01+0200)
Java version: 1.6.0_20
Java home: /usr/lib/jvm/java-6-sun-1.6.0.20/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux" version: "2.6.32-23-generic" arch: "i386" Family: "unix"
```

Should I create a separate issue?

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

the real bug is in the archetype: this descriptor doesn't support any id attribute.
[An xsd has been defined](http://maven.apache.org/archetype/archetype-common/archetype-descriptor.html) to help people write correct descriptors...

BTW, I disabled strict xml parsing in r984974 to avoid direct failure in such a case

**Comment by jira-importer** [comment]
**[Luca Masini](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=masini)** commented

You can use 2.0-alpha-4, all works great with that maven-archetype-plugin version.
Ciao.
