### ISSUE TITLE
[ARCHETYPE-10] j2ee archetype has invalid dependencies

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#423]
**[Brian Bonner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bkbonner)** opened **[ARCHETYPE-10](https://issues.apache.org/jira/browse/ARCHETYPE-10?redirect=false)** and commented

I'm trying to install the maven-j2ee-archetype and run it to test a mod to the eclipse plugin that I made.

Unfortunately, it's not letting me install the archetype.

I unpacked:  maven-archetype-j2ee.jar

I cd'd to the directory and ran:  mvn install.

C:\test\maven-archetype-j2ee>mvn install
[INFO] Scanning for projects...
Downloading: http://cvs.apache.org/repository//org/apache/maven/archetypes/maven
-archetypes/1.0-alpha-4-SNAPSHOT/maven-archetypes-1.0-alpha-4-SNAPSHOT.pom
[WARNING] Unable to get resource from repository snapshot-repo (http://cvs.apach
e.org/repository/)
[INFO] -------------------------------------------------------------------------
&mdash;
[ERROR] FATAL ERROR
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Failed to resolve artifact.

GroupId: org.apache.maven.archetypes
ArtifactId: maven-archetypes
Version: 1.0-alpha-4-SNAPSHOT

Reason: Unable to download the artifact from any repository
org.apache.maven.archetypes:maven-archetypes:1.0-alpha-4-SNAPSHOT:pom

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshot-repo (http://cvs.apache.org/repository/)

[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: POM 'org.apache.maven.archetyp
es:maven-archetypes' not found in repository: Unable to download the artifact fr
om any repository
org.apache.maven.archetypes:maven-archetypes:1.0-alpha-4-SNAPSHOT:pom

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshot-repo (http://cvs.apache.org/repository/)

    at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:359)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:276)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.

java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.project.ProjectBuildingException: POM 'org.apache.ma
ven.archetypes:maven-archetypes' not found in repository: Unable to download the
artifact from any repository
org.apache.maven.archetypes:maven-archetypes:1.0-alpha-4-SNAPSHOT:pom

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshot-repo (http://cvs.apache.org/repository/)

    at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepo

sitory(DefaultMavenProjectBuilder.java:423)
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(D
efaultMavenProjectBuilder.java:955)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMave
nProjectBuilder.java:586)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFi
le(DefaultMavenProjectBuilder.java:298)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMave
nProjectBuilder.java:276)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:509)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:441)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:345)
... 11 more
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException: Unable
to download the artifact from any repository
org.apache.maven.archetypes:maven-archetypes:1.0-alpha-4-SNAPSHOT:pom

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshot-repo (http://cvs.apache.org/repository/)

    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(De

faultArtifactResolver.java:136)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(De
faultArtifactResolver.java:63)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepo
sitory(DefaultMavenProjectBuilder.java:380)
... 18 more
Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Unable to downl
oad the artifact from any repository
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(Def
aultWagonManager.java:260)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(De
faultArtifactResolver.java:124)
... 20 more
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Total time: < 1 second
[INFO] Finished at: Thu Oct 27 11:01:13 EDT 2005
[INFO] Final Memory: 1M/2M
[INFO] -------------------------------------------------------------------------
&mdash;

C:\test\maven-archetype-j2ee>

I added the snapshot repository to my settings.xml, (more or less hoping the snapshot would be in there), to no avail.  I subsequently checked and verified that it was not there.

Any thoughts?

---

**Attachments:**
- [marchetype-10.patch](https://issues.apache.org/jira/secure/attachment/12713727/marchetype-10.patch) (_3.21 kB_)

**Comment by jira-importer** [comment]
**[Brian Bonner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bkbonner)** commented

Also in ARCHETYPE-8 the sample jar files:

root.project:primary-source:jar:1.0 depends on wsdl4j:wsdl4j:1.5.1:jar

I couldn't find this jar anywhere in ibiblio, but I did find axis:axis-wsld4j:1.5.1:jar

I repored this on MEV-151

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

the versions have all been aligned for the 1.0-alpha-4 release, but the dependency still needs to be investigated.

**Comment by jira-importer** [comment]
**[Jesse McConnell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jmcconnell)** commented

well, nothing in there strictly needs to require webservices I don't think

I'll take a look, I probably built the sample around the idea of webservices as well

**Comment by jira-importer** [comment]
**[Jesse McConnell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jmcconnell)** commented

removed the references to axis and fop...they really shouldn't have been there in the first place...what was I thinking! :)

**Comment by jira-importer** [comment]
**[Jesse McConnell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jmcconnell)** commented

here you go brett, just wacking things out of the poms.

**Comment by jira-importer** [comment]
**[Jesse McConnell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jmcconnell)** commented

I was able to get this commited and a vote on the plugin has been called
