### ISSUE TITLE
[ARCHETYPE-456] Add an option to allow comparing reference project to generated one regardless of the EOL encoding

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#441]
**[Baptiste MATHUS](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mathus.b@mipih.fr)** opened **[ARCHETYPE-456](https://issues.apache.org/jira/browse/ARCHETYPE-456?redirect=false)** and commented

Mojo : archetype:integration-test

Currently, depending on where you created the reference project to be compared to the generated one, the test can fail.

This feature would add an option to ask for comparison saying basically you don't care it's a CR, a LF, or a CRLF EOL, and are only interested in the rest of the content.

I'm also including a patch (which also includes the corresponding IT for the invoker-plugin).

---

**Affects:** 2.2

**Attachments:**
- [ARCHETYPE-ignoreEOLEncoding-v2.patch](https://issues.apache.org/jira/secure/attachment/12713884/ARCHETYPE-ignoreEOLEncoding-v2.patch) (_29.00 kB_)
- [build-archetype-ignore-eol-encoding.zip](https://issues.apache.org/jira/secure/attachment/12713719/build-archetype-ignore-eol-encoding.zip) (_22.22 kB_)

**Issue Links:**
- [ARCHETYPE-410](https://issues.apache.org/jira/browse/ARCHETYPE-410) The goal archetype:integration-test should ignore line ending when comparing the generated project to the reference
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Baptiste MATHUS](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mathus.b@mipih.fr)** commented

Woops, just noticed I did the patch against the 2.2. Currently reworking it to apply on the trunk, sorry about that.

**Comment by jira-importer** [comment]
**[Baptiste MATHUS](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mathus.b@mipih.fr)** commented

New version of the patch.

Not sure at all though that the patch format is gonna retain the necessarily different newline encodings (LF, CR instead of a single one and so on). So, I'm also attaching a zipped version of the new it directory.

The ITs is actually composed of two runs, the first one **must** fail (without enabling the ignoreEOLEncoding new behaviour).

**Comment by jira-importer** [comment]
**[Stephen Connolly](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stephenc)** commented

The patch as currently supplied does not work as the integration tests have an implicit assumption that the install phase is invoked.

```
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.apache.maven.archetype:archetype-packaging:2.3-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.apache.maven.archetype:archetype-packaging:jar:2.3-SNAPSHOT in local.central (file:///Users/stephenc/.m2/repository) @ 
[ERROR] Unknown packaging: maven-archetype @ line 29, column 14

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:364)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:672)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:663)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:250)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project org.apache.maven.plugins.archetype.its:build-archetype:1.0-SNAPSHOT (/Users/stephenc/apache/maven-archetype/maven-archetype-plugin/target/it/build-archetype/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.maven.archetype:archetype-packaging:2.3-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.apache.maven.archetype:archetype-packaging:jar:2.3-SNAPSHOT in local.central (file:///Users/stephenc/.m2/repository) -> [Help 2]
org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.archetype:archetype-packaging:2.3-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.apache.maven.archetype:archetype-packaging:jar:2.3-SNAPSHOT in local.central (file:///Users/stephenc/.m2/repository)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:208)
	at org.apache.maven.project.DefaultProjectBuildingHelper.resolveExtensionArtifacts(DefaultProjectBuildingHelper.java:380)
	at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm(DefaultProjectBuildingHelper.java:239)
	at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled(DefaultModelBuildingListener.java:110)
	at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire(ModelBuildingEventCatapult.java:43)
	at org.apache.maven.model.building.DefaultModelBuilder.fireEvent(DefaultModelBuilder.java:1069)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:385)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:368)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:561)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:353)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:672)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:663)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:250)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.apache.maven.archetype:archetype-packaging:jar:2.3-SNAPSHOT in local.central (file:///Users/stephenc/.m2/repository)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:459)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:200)
	... 24 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache.maven.archetype:archetype-packaging:jar:2.3-SNAPSHOT in local.central (file:///Users/stephenc/.m2/repository)
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$6.wrap(WagonRepositoryConnector.java:1012)
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$6.wrap(WagonRepositoryConnector.java:1004)
	at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:725)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
[ERROR]     Unknown packaging: maven-archetype @ line 29, column 14
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by jira-importer** [comment]
**[Baptiste MATHUS](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mathus.b@mipih.fr)** commented

IIUC, the IT you have in your logs is actually not mine but an existing one.

Mine is a slightly modified copy which is called build-archetype-ignore-eol-encoding which I can't find in your logs.

Just checked locally and 'mvn clean verify -Prun-its' works fine here with the patch (using the unzipped IT since the patch format unfortunately can't correctly handle&keep the newline mixes I've put in).

**Comment by jira-importer** [comment]
**[Baptiste MATHUS](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mathus.b@mipih.fr)** commented

Any comment in answer to my last one, Stephen?

**Comment by jira-importer** [comment]
**[Petar Tahchiev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paranoiabla)** commented

This patch works perfectly fine for me. I will polish it a bit and apply it to the master. Thank you Baptiste
