### ISSUE TITLE
[ARCHETYPE-32] including png in site resources breaks an archetype (stacktrace+archetype.xml included)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#458]
**[Jurgen De Landsheer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jurgendl)** opened **[ARCHETYPE-32](https://issues.apache.org/jira/browse/ARCHETYPE-32?redirect=false)** and commented

if I drop the png: creation is correct but it seems it wants to parse a png or something?

\<archetype>
	\<id>maven-ugent-plugin-archetype\</id>
	\<sources>
		\<source>
			src/main/java/org/codehaus/mojo/test/TestMojo.java
		\</source>
	\</sources>
	\<testSources>
		\<source>
			src/test/java/org/codehaus/mojo/test/TestMojoTestSuite.java
		\</source>
	\</testSources>
	\<resources>
		\<resource>src/main/resources/jalopy.xml\</resource>
		\<resource>src/main/resources/plugin.properties\</resource>
	\</resources>
	\<testResources>
		\<resource>src/test/resources/test.properties\</resource>
	\</testResources>
	\<siteResources>
		\<resource>src/site/site.xml\</resource>
		\<resource>src/site/apt/usage.apt\</resource>
		\<resource>src/site/resources/images/logobalk_small.png\</resource>
	\</siteResources>
\</archetype>

C:\JAVA\maven-plugins>mvn -e archetype:create -DarchetypeGroupId=be.ugent.dict -DarchetypeArtifactId=maven-ugent-plugin-archetype -DgroupId= -DartifactId=test

C:\JAVA\maven-plugins>set MAVEN_OPTS=-Xmx32m -Xmx200m
+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Reactor build order:
  [INFO]   maven-ugent-plugin-archetype
  [INFO]   maven-mojo-report-plugin
  [INFO]   maven-lint4j-plugin
  [INFO]   maven-juge-plugin
  [INFO]   maven-project-info-plugin
  [INFO]   maven-spring-beandoc-plugin
  [INFO]   maven-linguine-maps-plugin
  [INFO]   maven-hibernate-tools-plugin
  [INFO] Searching repository for plugin with prefix: 'archetype'.
  [INFO] org.apache.maven.plugins: checking for updates from missing-plugins
  [INFO] org.apache.maven.plugins: checking for updates from ugent-plugins
  [INFO] org.codehaus.mojo: checking for updates from missing-plugins
  [INFO] org.codehaus.mojo: checking for updates from ugent-plugins
  [INFO] artifact org.apache.maven.plugins:maven-compiler-plugin: checking for updates from missing-plugins
  [INFO] artifact org.apache.maven.plugins:maven-compiler-plugin: checking for updates from ugent-plugins
  [INFO] artifact org.apache.maven.plugins:maven-site-plugin: checking for updates from missing-plugins
  [INFO] artifact org.apache.maven.plugins:maven-site-plugin: checking for updates from ugent-plugins
  [INFO] artifact org.apache.maven.plugins:maven-surefire-plugin: checking for updates from missing-plugins
  [INFO] artifact org.apache.maven.plugins:maven-surefire-plugin: checking for updates from ugent-plugins
  [INFO] artifact org.apache.maven.plugins:maven-archetype-plugin: checking for updates from missing-plugins
  [INFO] artifact org.apache.maven.plugins:maven-archetype-plugin: checking for updates from ugent-plugins
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building maven-mojo-report-plugin
  [INFO]    task-segment: [archetype:create] (aggregator-style)
  [INFO] ----------------------------------------------------------------------------
  [INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
  [INFO] Setting property: resource.loader => 'classpath'.
  [INFO] **************************************************************
  [INFO] Starting Jakarta Velocity v1.4
  [INFO] RuntimeInstance initializing.
  [INFO] Default Properties File: org\apache\velocity\runtime\defaults\velocity.properties
  [INFO] Default ResourceManager initializing. (class org.apache.velocity.runtime.resource.ResourceManagerImpl)
  [INFO] Resource Loader Instantiated: org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
  [INFO] ClasspathResourceLoader : initialization starting.
  [INFO] ClasspathResourceLoader : initialization complete.
  [INFO] ResourceCache : initialized. (class org.apache.velocity.runtime.resource.ResourceCacheImpl)
  [INFO] Default ResourceManager initialization complete.
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Literal
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Include
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
  [INFO] Created: 20 parsers.
  [INFO] Velocimacro : initialization starting.
  [INFO] Velocimacro : adding VMs from VM library template : VM_global_library.vm
  [ERROR] ResourceManager : unable to find resource 'VM_global_library.vm' in any resource loader.
  [INFO] Velocimacro : error using  VM library template VM_global_library.vm : org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'VM_global_library.vm'
  [INFO] Velocimacro :  VM library template macro registration complete.
  [INFO] Velocimacro : allowInline = true : VMs can be defined inline in templates
  [INFO] Velocimacro : allowInlineToOverride = false : VMs defined inline may NOT replace previous VM definitions
  [INFO] Velocimacro : allowInlineLocal = false : VMs defined inline will be  global in scope if allowed.
  [INFO] Velocimacro : messages on  : VM system will output logging messages
  [INFO] Velocimacro : autoload off  : VM system will not automatically reload global library macros
  [INFO] Velocimacro : initialization complete.
  [INFO] Velocity successfully started.
  [INFO] [archetype:create]
  [INFO] Defaulting package to group ID:
  [INFO] artifact be.ugent.dict:maven-ugent-plugin-archetype: checking for updates from ugent-repository
  [INFO] artifact be.ugent.dict:maven-ugent-plugin-archetype: checking for updates from missing-artifacts
  [INFO] ----------------------------------------------------------------------------
  [INFO] Using following parameters for creating Archetype: maven-ugent-plugin-archetype:RELEASE
  [INFO] ----------------------------------------------------------------------------
  [INFO] Parameter: groupId, Value:
  [INFO] Parameter: outputDirectory, Value: C:\JAVA\maven-plugins\test
  [INFO] Parameter: packageName, Value:
  [INFO] Parameter: package, Value:
  [INFO] Parameter: version, Value: 1.0-SNAPSHOT
  [INFO] Parameter: artifactId, Value: test
  [INFO] ResourceManager : found archetype-resources/pom.xml with loader org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
  [INFO] ********************* End of debug info from resources from generated POM ***********************
  [INFO] ResourceManager : found archetype-resources/src/main/java/org/codehaus/mojo/test/TestMojo.java with loader org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/java/org/codehaus/mojo/test/TestMojo.java [line 84,column 31] : ${project.build.directory} is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/java/org/codehaus/mojo/test/TestMojo.java [line 93,column 31] : ${project.build.outputDirectory} is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/java/org/codehaus/mojo/test/TestMojo.java [line 102,column 31] : ${project.reporting.outputDirectory} is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/java/org/codehaus/mojo/test/TestMojo.java [line 111,column 31] : ${project.build.sourceDirectory} is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/java/org/codehaus/mojo/test/TestMojo.java [line 120,column 31] : ${project} is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/java/org/codehaus/mojo/test/TestMojo.java [line 129,column 31] : ${component.org.codehaus.doxia.site.renderer.SiteRenderer} is not a valid reference.
  [INFO] ResourceManager : found archetype-resources/src/main/resources/jalopy.xml with loader org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/resources/jalopy.xml [line 185,column 56] : $author is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/resources/jalopy.xml [line 185,column 77] : $Revision is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/resources/jalopy.xml [line 188,column 47] : $exceptionType is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/resources/jalopy.xml [line 189,column 42] : $paramType is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/resources/jalopy.xml [line 190,column 51] : $objectType is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/resources/jalopy.xml [line 192,column 60] : $author is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/resources/jalopy.xml [line 192,column 81] : $Revision is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/resources/jalopy.xml [line 195,column 47] : $exceptionType is not a valid reference.
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/main/resources/jalopy.xml [line 196,column 42] : $paramType is not a valid reference.
  [INFO] ResourceManager : found archetype-resources/src/main/resources/plugin.properties with loader org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
  [INFO] ResourceManager : found archetype-resources/src/test/java/org/codehaus/mojo/test/TestMojoTestSuite.java with loader org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
  [INFO] ResourceManager : found archetype-resources/src/test/resources/test.properties with loader org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
  [INFO] ResourceManager : found archetype-resources/src/site/site.xml with loader org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
  [WARNING] org.apache.velocity.runtime.exception.ReferenceException: reference : template = archetype-resources/src/site/site.xml [line 20,column 7] : ${reports} is not a valid reference.
  [INFO] ResourceManager : found archetype-resources/src/site/apt/usage.apt with loader org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
  [ERROR] ResourceManager.getResource() parse exception: org.apache.velocity.exception.ParseErrorException: Lexical error: org.apache.velocity.runtime.parser.TokenMgrError: Lexical error at line 133, column 107.  Encountered: \<EOF> after : ""
  [INFO] ----------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ----------------------------------------------------------------------------
  [INFO] Error creating from archetype

Embedded error: Error processing templates.
Lexical error: org.apache.velocity.runtime.parser.TokenMgrError: Lexical error at line 133, column 107.  Encountered: \<EOF> after : ""
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error creating from archetype
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:485)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:455)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:216)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating from archetype
at org.apache.maven.plugin.archetype.MavenArchetypeMojo.execute(MavenArchetypeMojo.java:157)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:415)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:531)
... 16 more
Caused by: org.apache.maven.archetype.ArchetypeTemplateProcessingException: Error processing templates.
at org.apache.maven.archetype.DefaultArchetype.createArchetype(DefaultArchetype.java:372)
at org.apache.maven.plugin.archetype.MavenArchetypeMojo.execute(MavenArchetypeMojo.java:144)
... 18 more
Caused by: org.apache.velocity.exception.ParseErrorException: Lexical error: org.apache.velocity.runtime.parser.TokenMgrError: Lexical error at line 133, column 107.  Encountered: \<EOF> after : ""
at org.apache.velocity.Template.process(Template.java:141)
at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:423)
at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:341)
at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:831)
at org.apache.velocity.app.VelocityEngine.mergeTemplate(VelocityEngine.java:440)
at org.apache.velocity.app.VelocityEngine.mergeTemplate(VelocityEngine.java:419)
at org.apache.maven.archetype.DefaultArchetype.processTemplate(DefaultArchetype.java:449)
at org.apache.maven.archetype.DefaultArchetype.processResources(DefaultArchetype.java:411)
at org.apache.maven.archetype.DefaultArchetype.createArchetype(DefaultArchetype.java:366)
... 19 more
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Fri Mar 03 15:07:59 CET 2006
[INFO] Final Memory: 5M/10M
[INFO] ------------------------------------------------------------------------

---

3 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

I have a slightly different issue, though probably related. Include any binary as a resource and it is filtered, thereby rendering it useless. No error though.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

are you using the latest from SVN? this was fixed in ARCHETYPE-19.

**Comment by jira-importer** [comment]
**[Sylvain Mougenot](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=neokiki2000)** commented

There are some non documented attributes that helped me solving this issue see http://jira.codehaus.org/browse/ARCHETYPE-19.

Like :
<resource **filtered="false"**>src/site/resources/images/logobalk_small.png\</resource>

**Comment by jira-importer** [comment]
**[Jurgen De Landsheer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jurgendl)** commented

maybe the field 'filtered' should be automatically set to false on binary files as I see no reason at all to filter them
and even most textual files do not need to be filtered, so setting filtered to false on all files would be ok for me

images (jpg, jpeg, png, etc)
documents (pdf)
etc

**Comment by jira-importer** [comment]
**[Raphael Luta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphael)** commented

This issue will be fixed by NG-alpha-1

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Addressed in ArchetypeNG.
