### ISSUE TITLE
[ARCHETYPE-36] j2ee-simple archetype causes error

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#459]
**[Alex Mayorga Adame](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alex_mayorga)** opened **[ARCHETYPE-36](https://issues.apache.org/jira/browse/ARCHETYPE-36?redirect=false)** and commented

Something seems to be missing inside the archetype.

Here's the stack trace for what is worth:

```none
bash-2.03$ mvn archetype:create -DgroupId=com.mycompany.app -DartifactId=j2ee-simple -DarchetypeArtifactId=maven-archetype-j2ee-simple -e
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'archetype'.
[INFO] ----------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO]    task-segment: [archetype:create] (aggregator-style)
[INFO] ----------------------------------------------------------------------------
[INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[INFO] Setting property: velocimacro.messages.on => 'false'.
[INFO] Setting property: resource.loader => 'classpath'.
[INFO] Setting property: resource.manager.logwhenfound => 'false'.
[INFO] **************************************************************
[INFO] Starting Jakarta Velocity v1.4
[INFO] RuntimeInstance initializing.
[INFO] Default Properties File: org/apache/velocity/runtime/defaults/velocity.properties
[INFO] Default ResourceManager initializing. (class org.apache.velocity.runtime.resource.ResourceManagerImpl)
[INFO] Resource Loader Instantiated: org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
[INFO] ClasspathResourceLoader : initialization starting.
[INFO] ClasspathResourceLoader : initialization complete.
[INFO] ResourceCache : initialized. (class org.apache.velocity.runtime.resource.ResourceCacheImpl)
[INFO] Default ResourceManager initialization complete.
[INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Literal
[INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
[INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
[INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Include
[INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
[INFO] Created: 20 parsers.
[INFO] Velocimacro : initialization starting.
[INFO] Velocimacro : adding VMs from VM library template : VM_global_library.vm
[ERROR] ResourceManager : unable to find resource 'VM_global_library.vm' in any resource loader.
[INFO] Velocimacro : error using  VM library template VM_global_library.vm : org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'VM_global_library.vm'
[INFO] Velocimacro :  VM library template macro registration complete.
[INFO] Velocimacro : allowInline = true : VMs can be defined inline in templates
[INFO] Velocimacro : allowInlineToOverride = false : VMs defined inline may NOT replace previous VM definitions
[INFO] Velocimacro : allowInlineLocal = false : VMs defined inline will be  global in scope if allowed.
[INFO] Velocimacro : initialization complete.
[INFO] Velocity successfully started.
[INFO] [archetype:create]
[INFO] Defaulting package to group ID: com.mycompany.app
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating Archetype: maven-archetype-j2ee-simple:RELEASE
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.mycompany.app
[INFO] Parameter: packageName, Value: com.mycompany.app
[INFO] Parameter: basedir, Value: /export1/eae/am74839/demos
[INFO] Parameter: package, Value: com.mycompany.app
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: artifactId, Value: j2ee-simple
[INFO] ********************* End of debug info from resources from generated POM ***********************
[ERROR] ResourceManager : unable to find resource 'archetype-resources/site/pom.xml' in any resource loader.
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error creating from archetype

Embedded error: Error merging velocity templates
Unable to find resource 'archetype-resources/site/pom.xml'
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error creating from archetype
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:559)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:488)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:219)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating from archetype
        at org.apache.maven.plugin.archetype.MavenArchetypeMojo.execute(MavenArchetypeMojo.java:201)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
        ... 16 more
Caused by: org.apache.maven.archetype.ArchetypeTemplateProcessingException: Error merging velocity templates
        at org.apache.maven.archetype.DefaultArchetype.processTemplate(DefaultArchetype.java:876)
        at org.apache.maven.archetype.DefaultArchetype.processTemplate(DefaultArchetype.java:730)
        at org.apache.maven.archetype.DefaultArchetype.processResources(DefaultArchetype.java:777)
        at org.apache.maven.archetype.DefaultArchetype.processTemplates(DefaultArchetype.java:687)
        at org.apache.maven.archetype.DefaultArchetype.createArchetype(DefaultArchetype.java:329)
        at org.apache.maven.plugin.archetype.MavenArchetypeMojo.execute(MavenArchetypeMojo.java:188)
        ... 18 more
Caused by: org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'archetype-resources/site/pom.xml'
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:458)
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:341)
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:831)
        at org.apache.velocity.app.VelocityEngine.mergeTemplate(VelocityEngine.java:440)
        at org.apache.maven.archetype.DefaultArchetype.processTemplate(DefaultArchetype.java:870)
        ... 23 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8 seconds
[INFO] Finished at: Mon May 22 13:36:53 EDT 2006
[INFO] Final Memory: 6M/77M
[INFO] ------------------------------------------------------------------------
```

---

**Affects:** 1.0-alpha-4

**Attachments:**
- [ARCHETYPE-36-maven-archetype-parent.patch](https://issues.apache.org/jira/secure/attachment/12713816/ARCHETYPE-36-maven-archetype-parent.patch) (_1.54 kB_)

**Comment by jira-importer** [comment]
**[Jesse McConnell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jmcconnell)** commented

removed the offending reference from the archetype.xml file, it was removed so this plugin played nicely with the site archetype

**Comment by jira-importer** [comment]
**[Franz Allan Valencia See](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=franz_see)** commented

Good day,

I checked out the current version of maven-archetype-j2ee-simple and the "offending references" of the archetype.xml were still there.  I've also tried using the command posted in the description and it also failed (as well as my other tries  to use it).

However, I created a patch to fix the problem. May I request that this issue be reopened so that I can attach the patch.

Thanks a bunch

-Franz

**Comment by jira-importer** [comment]
**[Allan Q. Ramirez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aramirez)** commented

confirmed

**Comment by jira-importer** [comment]
**[Franz Allan Valencia See](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=franz_see)** commented

In maven-archetype\maven-archetype-plugin\src\main\java\org\apache\maven\plugin\archetype\MavenArchetypeMojo.java
changed the default-value of the archetypeGroupId from "org.apache.maven.archetypes" to "org.apache.maven.archetype"

In maven-archetype-bundles\maven-archetype-j2ee-simple\src\main\resources\META-INF\archetype.xml
removed the following lines:
\<resource>site/pom.xml\</resource>
\<resource>site/src/site/site.xml\</resource>
\<resource>site/src/site/apt/site.apt\</resource>
which Jesse McConnell mentioned as the solution.

**Comment by jira-importer** [comment]
**[Allan Q. Ramirez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aramirez)** commented

Patch applied. Thanks
