### ISSUE TITLE
[ARCHETYPE-67] j2ee archetype unbuildable

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#480]
**[Eric Redmond](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eredmond)** opened **[ARCHETYPE-67](https://issues.apache.org/jira/browse/ARCHETYPE-67?redirect=false)** and commented

The archetype pom contains a "site" module that is not created when running the archetype. Please remove.

---

**Affects:** 1.0-alpha-5

2 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Michael Greifeneder](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mikegr)** commented

I have installed Maven 2.0.6 and would like to create a j2ee-simple project with

mvn archetype:create -DgroupId=my.group.id -DartifactId=MyArtifact -DarchetypeArtifactId=maven-archetype-j2ee-simple

However it's missing a site project and names aren't set correctly in POM file in my opinion:

org.apache.maven.reactor.MavenExecutionException: Could not find the model file '/tmp/MyRoot/MyArtifact/site/pom.xml'.

\<project>
\<modelVersion>4.0.0\</modelVersion>
\<groupId>root\</groupId>
\<version>1.0\</version>
\<artifactId>project\</artifactId>
\<packaging>pom\</packaging>
\<name>project\</name>

**Comment by jira-importer** [comment]
**[Alexander Zynevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zynevich)** commented

got absolutly the same in Win:
C:\alex\workspace>mvn archetype:create -DartifactId=simple -DgroupId=simple -Dar
chetypeArtifactId=maven-archetype-j2ee-simple

succefull!

but:

C:\alex\workspace\simple>mvn compile
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: unknown

Reason: Could not find the model file 'C:\alex\workspace\simple\site\pom.xml'.

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Could not find the model file
'C:\alex\workspace\simple\site\pom.xml'.
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:378)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:290)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.project.ProjectBuildingException: Could not find the
model file 'C:\alex\workspace\simple\site\pom.xml'.
at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(Default
MavenProjectBuilder.java:1384)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFi
leInternal(DefaultMavenProjectBuilder.java:477)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMave
nProjectBuilder.java:200)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:537)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:467)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:511)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:364)
... 11 more
Caused by: java.io.FileNotFoundException: C:\alex\workspace\simple\site\pom.xml
(The system cannot find the path specified)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.\<init>(FileInputStream.java:106)
at java.io.FileReader.\<init>(FileReader.java:55)
at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(Default
MavenProjectBuilder.java:1379)
... 17 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Thu May 10 15:39:15 EEST 2007
[INFO] Final Memory: 1M/2M
[INFO] ------------------------------------------------------------------------

C:\alex\workspace\simple>
