### ISSUE TITLE
[ARCHETYPE-69] Resource filtering fails for Freemarker templates

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#489]
**[leandro moreira](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=leandro)** opened **[ARCHETYPE-69](https://issues.apache.org/jira/browse/ARCHETYPE-69?redirect=false)** and commented

Using

```xml
<resources>
  <resource filtered="false">Template.ftl</resource> 
</resources>
```

fails. Velocity still tries to parse the file, leading to an error:

```
[ERROR] Parser Exception: archetype-resources/Template.ftl : org.apache.velocity.runtime.parser.ParseException: Encountered "data" at line 28, column 30.
Was expecting:
    "(" ...
    
        at org.apache.velocity.runtime.parser.Parser.generateParseException(Parser.java:3271)
        at org.apache.velocity.runtime.parser.Parser.jj_consume_token(Parser.java:3155)
        at org.apache.velocity.runtime.parser.Parser.IfStatement(Parser.java:1284)
        at org.apache.velocity.runtime.parser.Parser.Statement(Parser.java:293)
        at org.apache.velocity.runtime.parser.Parser.process(Parser.java:258)
        at org.apache.velocity.runtime.parser.Parser.parse(Parser.java:104)
        at org.apache.velocity.runtime.RuntimeInstance.parse(RuntimeInstance.java:776)
        at org.apache.velocity.runtime.RuntimeInstance.parse(RuntimeInstance.java:720)
        at org.apache.velocity.Template.process(Template.java:123)
```

---
No further details from [ARCHETYPE-69](https://issues.apache.org/jira/browse/ARCHETYPE-69?redirect=false)

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Issue seems to refer to http://maven.apache.org/archetype/archetype-common/archetype.html

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
