### ISSUE TITLE
[ARCHETYPE-107] maven archetype missing dependency versions breaks archetype:create 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#529]
**[Andrew Waterman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=awaterma)** opened **[ARCHETYPE-107](https://issues.apache.org/jira/browse/ARCHETYPE-107?redirect=false)** and commented

When I try to invoke the "create" goal in the 2.0.7 version of maven, I receive the following error message when invoked from a directory with an existing pom.xml:

Project ID: org.apache.maven.plugins:maven-archetype-plugin
POM Location: Artifact [org.apache.maven.plugins:maven-archetype-plugin:pom:1.0-SNAPSHOT]
Validation Messages:

    [0]  'dependencies.dependency.version' is missing for org.apache.maven.archetype:maven-archetype-creator

Reason: Failed to validate POM for project org.apache.maven.plugins:maven-archetype-plugin at Artifact [org.apache.maven.plugins:maven-archetype-plugin:pom:1.0-SNAPSHOT]

The currently staged version of the maven-archetype-creator dependency contains a missing version reference:

\<dependency>
\<groupId>org.apache.maven.archetype\</groupId>
\<artifactId>maven-archetype-model\</artifactId>
\</dependency>
[source:  http://repo1.maven.org/maven2/org/apache/maven/archetype/maven-archetype-creator/1.0-alpha-7/maven-archetype-creator-1.0-alpha-7.pom]
This effectively breaks the archetype:create goal.

---

6 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Andreas Höhmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ahoehma)** commented

i have the same problem under winxp/jdk1.5/maven 2.0.7 **but** not at all!
i have a test-project where the archetype:create works great but i have a
other project (with a lot of sub/sub/projects, reports, etc.) where this error
happend every time. i can provide the parent-pom if this helps.

**Comment by jira-importer** [comment]
**[kris beaumont](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=beaumkr)** commented

[edit]
tried upgrading, same result: environment:

D:\struts2\multimoduletest\MyProject>mvn -version
Maven version: 2.0.8
Java version: 1.6.0_03
OS name: "windows xp" version: "5.1" arch: "x86" Family: "windows"
[/edit]

I think he can't handle the SNAPSHOT default value in some archetypes.
He first says he's ignoring the value and then he says it missing and therefor fails to validate the POM.

below is the output on my screen (and my maven version).

[INFO] Searching repository for plugin with prefix: 'archetype'.
[WARNING] POM for 'org.apache.maven.plugins:maven-archetype-plugin:pom:1.0-SNAPSHOT' is invalid. It will be ig
nored for artifact resolution. Reason: Failed to validate POM
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: org.apache.maven.plugins:maven-archetype-plugin
POM Location: Artifact [org.apache.maven.plugins:maven-archetype-plugin:pom:1.0-SNAPSHOT]
Validation Messages:

    [0]  'dependencies.dependency.version' is missing for org.apache.maven.archetype:maven-archetype-creator

Reason: Failed to validate POM

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Unable to build project information for plugin 'org.ap
ache.maven.plugins:maven-archetype-plugin': Failed to validate POM
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1274
)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getMojoDescriptor(DefaultLifecycleExecutor.java
:1522)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.segmentTaskListByAggregationNeeds(DefaultLifecy
cleExecutor.java:386)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:138)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.InvalidPluginException: Unable to build project information for plugin 'org
.apache.maven.plugins:maven-archetype-plugin': Failed to validate POM
at org.apache.maven.plugin.version.DefaultPluginVersionManager.resolveMetaVersion(DefaultPluginVersion
Manager.java:704)
at org.apache.maven.plugin.version.DefaultPluginVersionManager.resolvePluginVersion(DefaultPluginVersi
onManager.java:186)
at org.apache.maven.plugin.version.DefaultPluginVersionManager.resolvePluginVersion(DefaultPluginVersi
onManager.java:90)
at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:166)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1257
)
... 14 more
Caused by: org.apache.maven.project.InvalidProjectModelException: Failed to validate POM
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.
java:1005)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:8
08)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.
java:236)
at org.apache.maven.plugin.version.DefaultPluginVersionManager.resolveMetaVersion(DefaultPluginVersion
Manager.java:698)
... 18 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Thu Dec 13 14:55:30 CET 2007
[INFO] Final Memory: 1M/4M
[INFO] ------------------------------------------------------------------------

D:\struts2\multimoduletest\myProject>mvn -version
Maven version: 2.0.6

**Comment by jira-importer** [comment]
**[Dave Minter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dcminter)** commented

Still an issue as of Maven versions 2.0.7 and 2.0.8.

Is there some obvious work-around aside from temporarily renaming the top level pom, hacking the generated poms to refer to the parent, and putting the parent back again?

As I understand this is a result of a bad pom in the archives. Is there a corrected pom that I could put into my local respository? (Hacking the pom directory to add an explicit version to the maven-archetype-model artifact didn't fix the problem).

It seems strange that this isn't a problem for more people if there isn't a simple work-around...?

**Comment by jira-importer** [comment]
**[JR Boyens](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jboyens)** commented

The easiest workaround I've found is to explicitly name the version of the archetype plugin like this:

$ mvn org.apache.maven.plugins:maven-archetype-plugin:1.0-alpha-4:create

Note that you'll also have to explicitly specify the archetypeVersion too

**Comment by jira-importer** [comment]
**[JR Boyens](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jboyens)** commented

I was just informed that a total rewrite of the archetype plugin has taken place and it is available as archetypeng

i.e.: $ mvn archetypeng:create

**Comment by jira-importer** [comment]
**[Raphael Luta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphael)** commented

these issues are obsolete since the 2.0-alpha version of the plugin
