### ISSUE TITLE
[ARCHETYPE-137] Problem when setting default values for archetype-metadata.xml

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#547]
**[Dominique Jean-Prost](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=djeanprost)** opened **[ARCHETYPE-137](https://issues.apache.org/jira/browse/ARCHETYPE-137?redirect=false)** and commented

I have an archetype-metadata.xml like this :
\<archetype-descriptor name="archetype-jpa">
\<fileSets>
...
\<fileSets>
\<requiredProperties>
\<requiredProperty key="groupId">
\<defaultValue>com.dexia.sofaxis\</defaultValue>
\</requiredProperty>
< requiredProperty key="version">
\<defaultValue>1.0.0-SNAPSHOT\</defaultValue>
\</requiredProperty>
\</requiredProperties>
\</archetype-descriptor>

If I try to use this archetype, groupId and version are not asked on command line, but I then get the exception. If I remove the requiredProperty elements, I don't get it.

[ERROR] The archetype is not configured
org.apache.maven.archetype.exception.ArchetypeNotConfigured: The archetype is not configured
at org.apache.maven.archetype.generator.DefaultFilesetArchetypeGenerator.generateArchetype(DefaultFilesetArchetypeGenerator.java:98)
at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.processFileSetArchetype(DefaultArchetypeGenerator.java:215)
at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:130)
at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:290)
at org.apache.maven.archetype.DefaultArchetype.generateProjectFromArchetype(DefaultArchetype.java:75)
at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execute(CreateProjectFromArchetypeMojo.java:169)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:224)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Affects:** 2.0-alpha-2

**Attachments:**
- [archetype-jar.zip](https://issues.apache.org/jira/secure/attachment/12713798/archetype-jar.zip) (_3.22 kB_)

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Jared Bunting](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=deraj123)** commented

I'll add that I get this same error, even if I specify the groupId and version on the command line.

**Comment by jira-importer** [comment]
**[Raphael Luta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphael)** commented

Hi Dominique,

Can you please attach your archetype,
so i can use it for testing purpose.

Thanks,

Raphaël

**Comment by jira-importer** [comment]
**[Dominique Jean-Prost](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=djeanprost)** commented

An archetype that shows that even if a couple of properties are defined, then not prompted when configuration occurs, an error is raised telling archetype is not configured

**Comment by jira-importer** [comment]
**[Raphael Luta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphael)** commented

Fixed since revision 642628

tested on windows with
mvn archetype:generate -DarchetypeCatalog=local -B -DarchetypeVersion=1.0-SNAPSHOT -DarchetypeGroupId=test -DarchetypeArtifactId=archetype-jar -DgroupId=com.company.project -DartifactId=library -Dversion=1 -Dpackage=com.company.project

I must have modified the archetype pom.xml file. Here's the new content :

\<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

\<modelVersion>4.0.0\</modelVersion>

\<groupId>test\</groupId>

\<artifactId>archetype-jar\</artifactId>

\<name>archetype-jar\</name>

\<version>1.0-SNAPSHOT\</version>

\<packaging>maven-archetype\</packaging>

\<build>

    <extensions>
    
      <extension>
    
        <groupId>org.apache.maven.archetype</groupId>
    
        <artifactId>archetype-packaging</artifactId>
    
        <version>2.0-alpha-3-SNAPSHOT</version>
    
      </extension>
    
    </extensions>
    
    <plugins>
    
      <plugin>
    
        <artifactId>maven-archetype-plugin</artifactId>
    
        <version>2.0-alpha-3-SNAPSHOT</version>
    
        <extensions>true</extensions>
    
      </plugin>
    
    </plugins>

\</build>
\</project>
