### ISSUE TITLE
[ARCHETYPE-128] Unable to create a Cocoon app with Maven archetype: [WARNING] No archetype repository found.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#552]
**[Luca Morandini](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lmorandini@ieee.org)** opened **[ARCHETYPE-128](https://issues.apache.org/jira/browse/ARCHETYPE-128?redirect=false)** and commented

When the following command is issued:
mvn archetype:create -DarchetypeGroupId=org.apache.cocoon
-DarchetypeArtifactId=cocoon-22-archetype-block
-DarchetypeVersion=1.0.0-RC2 -DgroupId=org.cocoondev -DartifactId=geoid-core

Maven 2.0.7 reports this error:
[INFO] [archetype:create]
[WARNING] No archetype repository found.
[WARNING] Specified archetype not found.
Choose archetype:
1: internal -> appfuse-basic-jsf (AppFuse archetype for creating a web
application with Hibernate, Spring and JSF)
...

This was solved by specifying use of the 1.0-alpha-7 archetype version in command line:
org.apache.maven.plugins:maven-archetype-plugin:1.0-alpha-7:create ..

---

**Affects:** 2.0-alpha-1

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Alexander Semenov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bohtvaroh)** commented

I can complain to this to. So now, 2.0-alpha-1 is unusable.

**Comment by jira-importer** [comment]
**[Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)** commented

fixed in this revision
http://svn.apache.org/viewvc?rev=627055&view=rev

**Comment by jira-importer** [comment]
**[Francois Le Droff](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=francois.le.droff)** commented

I tried the fixed version 2.0-alpha1 and 3 without.
I installed my archetype on my .m2 repository, when I ran it, I got into issues, it was not found
So I created a local repo, I deployed my archetype on it.
I used this repo calling mvn archetype:create.

I failed,  here is the stack trace :

Reason: Unable to locate resource in repository

Try downloading the file manually from the project website.

Then, install it using the command:
mvn install:install-file -DgroupId=org.apache.maven.archetypes -DartifactId=
blazeds-xdoclet-spring-hibernate-archetype -Dversion=1.0 -Dpackaging=jar -Dfile=
/path/to/file

Alternatively, if you host your own repository you can deploy the file there:
mvn deploy:deploy-file -DgroupId=org.apache.maven.archetypes -DartifactId=bl
azeds-xdoclet-spring-hibernate-archetype -Dversion=1.0 -Dpackaging=jar -Dfile=/p
ath/to/file -Durl=[url] -DrepositoryId=[id]

org.apache.maven.archetypes:blazeds-xdoclet-spring-hibernate-archetype:jar:1.0

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
my-local-repository (file://C:/apps/adobe-m2-repository)

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error creating from arch
etype
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:583)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandalone
Goal(DefaultLifecycleExecutor.java:512)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:482)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:227)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at jrockit.reflect.InitialMethodInvoker.invoke(Ljava.lang.Object;[Ljava.
lang.Object;)Ljava.lang.Object;(Unknown Source)
at java.lang.reflect.Method.invoke(Ljava.lang.Object;[Ljava.lang.Object;
I)Ljava.lang.Object;(Unknown Source)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating from a
rchetype
at org.apache.maven.archetype.mojos.MavenArchetypeMojo.execute(MavenArch
etypeMojo.java:238)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:558)
... 14 more
Caused by: org.apache.maven.archetype.old.ArchetypeNotFoundException: OldArchety
pe does not exist.
at org.apache.maven.archetype.old.DefaultOldArchetype.createArchetype(De
faultOldArchetype.java:131)
at org.apache.maven.archetype.mojos.MavenArchetypeMojo.execute(MavenArch
etypeMojo.java:227)
... 16 more
Caused by: org.apache.maven.archetype.downloader.DownloadNotFoundException: Requ
ested download does not exist.
at org.apache.maven.archetype.downloader.DefaultDownloader.download(Defa
ultDownloader.java:62)
at org.apache.maven.archetype.old.DefaultOldArchetype.createArchetype(De
faultOldArchetype.java:122)
... 17 more
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException: Unable
to locate resource in repository

Try downloading the file manually from the project website.

Then, install it using the command:
mvn install:install-file -DgroupId=org.apache.maven.archetypes -DartifactId=
blazeds-xdoclet-spring-hibernate-archetype -Dversion=1.0 -Dpackaging=jar -Dfile=
/path/to/file

Alternatively, if you host your own repository you can deploy the file there:
mvn deploy:deploy-file -DgroupId=org.apache.maven.archetypes -DartifactId=bl
azeds-xdoclet-spring-hibernate-archetype -Dversion=1.0 -Dpackaging=jar -Dfile=/p
ath/to/file -Durl=[url] -DrepositoryId=[id]

org.apache.maven.archetypes:blazeds-xdoclet-spring-hibernate-archetype:jar:1.0

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
my-local-repository (file://C:/apps/adobe-m2-repository)

    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(De

faultArtifactResolver.java:212)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveAlw
ays(DefaultArtifactResolver.java:80)
at org.apache.maven.archetype.downloader.DefaultDownloader.download(Defa
ultDownloader.java:54)
... 18 more
Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Unable to locat
e resource in repository
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputD
ata(LightweightHttpWagon.java:100)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:68)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(D
efaultWagonManager.java:470)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(Def
aultWagonManager.java:354)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(De
faultArtifactResolver.java:196)
... 20 more
Caused by: java.io.FileNotFoundException: http://repo1.maven.org/maven2/org/apac
he/maven/archetypes/blazeds-xdoclet-spring-hibernate-archetype/1.0/blazeds-xdocl
et-spring-hibernate-archetype-1.0.jar
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1147)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputD
ata(LightweightHttpWagon.java:83)
... 24 more
