### ISSUE TITLE
[ARCHETYPE-144] Fails "archetype:create" when specify archetypeVersion

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#567]
**[BABA,Yasuyuki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baba@nulab.co.jp)** opened **[ARCHETYPE-144](https://issues.apache.org/jira/browse/ARCHETYPE-144?redirect=false)** and commented

We uses custom archetype and remote repository.
http://maven.seasar.org/maven2/org/seasar/cubby/cubby-archetype/1.0.0/cubby-archetype-1.0.0.jar

no specify "archetypeVersion" -> build successful

```
mvn archetype:create -DremoteRepositories=http://maven.seasar.org/maven2/ \
-DgroupId=com.example.foo -DartifactId=barapp -DarchetypeGroupId=org.seasar.cubby \
-DarchetypeArtifactId=cubby-archetype
```

specify "archetypeVersion" -> build error

```
mvn archetype:create -DremoteRepositories=http://maven.seasar.org/maven2/ \
-DgroupId=com.example.foo -DartifactId=barapp -DarchetypeGroupId=org.seasar.cubby \
-DarchetypeArtifactId=cubby-archetype -DarchetypeVersion=1.0.0
```

and part of log

```
[INFO] [archetype:create]
[INFO] Defaulting package to group ID: com.example.foo
[INFO] We are using command line specified remote repositories: http://maven.seasar.org/maven2/
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error creating from archetype

Embedded error: OldArchetype does not exist.
http://repo1.maven.org/maven2/org/seasar/cubby/cubby-archetype/1.0.0/cubby-archetype-1.0.0.jar
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ expects "http://maven.seasar.org/maven2/" !
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Mon Mar 03 21:16:46 JST 2008
[INFO] Final Memory: 8M/79M
[INFO] ------------------------------------------------------------------------
```

---

**Affects:** 2.0-alpha-2

**Issue Links:**
- [ARCHETYPE-150](https://issues.apache.org/jira/browse/ARCHETYPE-150) New maven-archetype-plugin ignores the remoteRepositories system property

**Comment by jira-importer** [comment]
**[Raphael Luta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphael)** commented

Using an archetype catalog should help.

i created such a catalog in the directory in which i call maven.

```
$ mvn archetype:generate -DarchetypeCatalog=file://archetype-catalog.xml
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'archetype'.
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO]    task-segment: [archetype:generate] (aggregator-style)
[INFO] ------------------------------------------------------------------------
[INFO] Preparing archetype:generate
[INFO] No goals needed for project - skipping
[INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[INFO] Setting property: velocimacro.messages.on => 'false'.
[INFO] Setting property: resource.loader => 'classpath'.
[INFO] Setting property: resource.manager.logwhenfound => 'false'.
[INFO] [archetype:generate]
Choose archetype:
1: local -> cubby-archetype (null)
Choose a number:  (1): 1
Define value for groupId: : com.company.cubby
Define value for artifactId: : test-cubby
Define value for version:  1.0-SNAPSHOT: : 1
Define value for package: : com.company.cubby.test
Confirm properties configuration:
groupId: com.company.cubby
artifactId: test-cubby
version: 1
package: com.company.cubby.test
 Y: : Y
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating OldArchetype: cubby-archetype:1.0.0
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.company.cubby
[INFO] Parameter: packageName, Value: com.company.cubby.test
[INFO] Parameter: package, Value: com.company.cubby.test
[INFO] Parameter: artifactId, Value: test-cubby
[INFO] Parameter: basedir, Value: /home/local/rafale/projects/tmp
[INFO] Parameter: version, Value: 1
[INFO] ********************* End of debug info from resources from generated POM ***********************
[INFO] OldArchetype created in dir: /home/local/rafale/projects/tmp/test-cubby
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48 seconds
[INFO] Finished at: Mon Mar 03 19:44:28 GMT 2008
[INFO] Final Memory: 11M/28M
[INFO] ------------------------------------------------------------------------
```

This catalog contains the xml:

```
<?xml version="1.0" encoding="UTF-8"?><archetype-catalog>
  <archetypes>
    <archetype>
      <groupId>org.seasar.cubby</groupId>
      <artifactId>cubby-archetype</artifactId>
      <version>1.0.0</version>
      <repository>http://maven.seasar.org/maven2</repository>
    </archetype>
  </archetypes>
</archetype-catalog>
```

You could create a catalog on a filesystem with the crawl mojo http://maven.apache.org/plugins/maven-archetype-plugin/crawl-mojo.html
and deploy it at the root of your repository.

Then call maven:

```
mvn archetype:generate -DarchetypeCatalog=http://maven.seasar.org/maven2
```

**Comment by jira-importer** [comment]
**[BABA,Yasuyuki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baba@nulab.co.jp)** commented

Thanks Raphael.
But, this case is the old "archetype:create".
Not "archetype:generate".

**Comment by jira-importer** [comment]
**[Raphael Luta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphael)** commented

The archetype:generate goal can recognise old archetype descriptors then redirect to old archetype:create.

I also tested archetype generate.

C:\Devs\jiras>mvn archetype:generate -DarchetypeRepository=http://maven.seasar.org/maven2/ -DgroupId=com.example.foo -DartifactId=barapp -Da
rchetypeGroupId=org.seasar.cubby -DarchetypeArtifactId=cubby-archetype -DarchetypeVersion=1.0.1 -B
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'archetype'.
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO]    task-segment: [archetype:generate] (aggregator-style)
[INFO] ------------------------------------------------------------------------
[INFO] Preparing archetype:generate
[INFO] No goals needed for project - skipping
Downloading: http://repo1.maven.org/maven2/com/example/foo/wagon-http-shared/1.0-beta-2/wagon-http-shared-1.0-beta-2.pom
Downloading: http://repo1.maven.org/maven2/com/example/foo/wagon-http-shared/1.0-beta-2/wagon-http-shared-1.0-beta-2.pom
[INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[INFO] Setting property: velocimacro.messages.on => 'false'.
[INFO] Setting property: resource.loader => 'classpath'.
[INFO] Setting property: resource.manager.logwhenfound => 'false'.
[INFO] [archetype:generate]
[INFO] Archetype defined by properties
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating OldArchetype: cubby-archetype:1.0.1
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.example.foo
[INFO] Parameter: packageName, Value: com.example.foo
[INFO] Parameter: basedir, Value: C:\Devs\jiras
[INFO] Parameter: package, Value: com.example.foo
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: artifactId, Value: barapp
[INFO] ********************* End of debug info from resources from generated POM ***********************
[INFO] OldArchetype created in dir: C:\Devs\jiras\barapp
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5 seconds
[INFO] Finished at: Thu Mar 13 23:57:19 CET 2008
[INFO] Final Memory: 7M/13M
[INFO] ------------------------------------------------------------------------

take care of replacing -DremoteRepositories by -DarchetypeRepository and also to use -B for batch mode.

**Comment by jira-importer** [comment]
**[BABA,Yasuyuki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baba@nulab.co.jp)** commented

Thank you.
Archetype generation succeed when I had the archetype artifact on my local repository.
But, has no archetype artifact on my local repo, unable to download archetype artifact and fails generation.

[baba@x61-baba ~]$ mvn archetype:generate -DarchetypeRepository=http://maven.seasar.org/maven2/ -DgroupId=com.example.foo -DartifactId=barapp -DarchetypeGroupId=org.seasar.cubby -DarchetypeArtifactId=cubby-archetype -DarchetypeVersion=1.0.1 -B
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'archetype'.
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO]    task-segment: [archetype:generate] (aggregator-style)
[INFO] ------------------------------------------------------------------------
[INFO] Preparing archetype:generate
[INFO] No goals needed for project - skipping
Downloading: http://repo1.maven.org/maven2/com/example/foo/wagon-http-shared/1.0-beta-2/wagon-http-shared-1.0-beta-2.pom
Downloading: http://repo1.maven.org/maven2/com/example/foo/wagon-http-shared/1.0-beta-2/wagon-http-shared-1.0-beta-2.pom
[INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[INFO] Setting property: velocimacro.messages.on => 'false'.
[INFO] Setting property: resource.loader => 'classpath'.
[INFO] Setting property: resource.manager.logwhenfound => 'false'.
[INFO] [archetype:generate]
[INFO] Archetype defined by properties
org.apache.maven.archetype.downloader.DownloadNotFoundException: Requested download does not exist.
at org.apache.maven.archetype.downloader.DefaultDownloader.download(DefaultDownloader.java:62)
at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.exists(DefaultArchetypeArtifactManager.java:310)
at org.apache.maven.archetype.ui.DefaultArchetypeGenerationConfigurator.configureArchetype(DefaultArchetypeGenerationConfigurator.java:103)
at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execute(CreateProjectFromArchetypeMojo.java:168)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:224)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException: Unable to download the artifact from any repository

Try downloading the file manually from the project website.

Then, install it using the command:
mvn install:install-file -DgroupId=org.seasar.cubby -DartifactId=cubby-archetype -Dversion=1.0.1 -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there:
mvn deploy:deploy-file -DgroupId=org.seasar.cubby -DartifactId=cubby-archetype -Dversion=1.0.1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

org.seasar.cubby:cubby-archetype:jar:1.0.1

    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:206)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveAlways(DefaultArtifactResolver.java:79)
    at org.apache.maven.archetype.downloader.DefaultDownloader.download(DefaultDownloader.java:54)
    ... 21 more

Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Unable to download the artifact from any repository
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:324)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:194)
... 23 more
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] The desired archetype does not exist (org.seasar.cubby:cubby-archetype:1.0.1)

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Fri Mar 14 08:13:10 JST 2008
[INFO] Final Memory: 8M/79M
[INFO] ------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Raphael Luta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphael)** commented

Fixed as a side effect of making the remoteRepositories/archetypeRepository property working
This issue ir related to ARCHETYPE-150
