### ISSUE TITLE
[ARCHETYPE-174] The archetype is not configured error does not provide error details

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#594]
**[Eugene Kuleshov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eu)** opened **[ARCHETYPE-174](https://issues.apache.org/jira/browse/ARCHETYPE-174?redirect=false)** and commented

When archetype is created (from ide) and does not specify required property, error message does not say what property is not specified. See test project attached at MNGECLIP[SE-612](https://issues.apache.org/jira/browse/SE-612)

org.apache.maven.archetype.exception.ArchetypeNotConfigured: The archetype is not configured
at org.apache.maven.archetype.generator.DefaultFilesetArchetypeGenerator.generateArchetype(DefaultFilesetArchetypeGenerator.java:98)
at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.processFileSetArchetype(DefaultArchetypeGenerator.java:215)
at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:130)
at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:290)
at org.apache.maven.archetype.DefaultArchetype.generateProjectFromArchetype(DefaultArchetype.java:75)
at org.maven.ide.eclipse.internal.project.ProjectConfigurationManager.createArchetypeProject(ProjectConfigurationManager.java:362)
at org.maven.ide.eclipse.wizards.MavenProjectWizard$4.runInWorkspace(MavenProjectWizard.java:227)
at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

---

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Raphael Luta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphael)** commented

Does the closing comment of ARCHETYPE-171 solves the problem?

**Comment by jira-importer** [comment]
**[Eugene Kuleshov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eu)** commented

If you are referring to [WARNING] entries in the log, then it is not sufficient.

We need a programmatic way to retrieve those warnings, so they could be shown in the wizard UI. Looking at your comment in that issue we still getting only "org.apache.maven.archetypes:maven-archetype-quickstart:1.0 is not configured" error, which isn't very helpful. That exception should contain all details about missing properties and provide accessors to retrive those details, so we could retrieve them in wizard UI.

On a side note, it would be more intuitive if error printed by mvn cli would look like the following, so you won't have to hunt for the warnings somewhere up in the log (perhaps by tuning toString() of the archetype exception):

```
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Archetype org.apache.maven.archetypes:maven-archetype-quickstart:1.0 is not configured
    Property groupId is missing. Add -DgroupId=someValue
    Property artifactId is missing. Add -DartifactId=someValue
    Property package is missing. Add -Dpackage=someValue
```

Also note that, "Add -DgroupId=someValue" text is unnecessary in the wizard UI as it would be confusing there, so error accessors shouldn't include this text.

**Comment by jira-importer** [comment]
**[Raphael Luta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphael)** commented

Fixed since revision 666805
The Exception thrown when the archetype is not configured now contains the list of the missing properties (when this list is revelant).
One can access that list using the getMissingProperties method that answers a list of strings.

**Comment by jira-importer** [comment]
**[Eugene Kuleshov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eu)** commented

Raphaël, not sure if it should be separate bug, but here is another issue with error reporting reported by users. So, the following exception have not detailed error (btw, this part is quite confusing:"[au.com.warpspeed.archetypes:basic-ear:1.0 -> null]") and we would have to hunt for the nested exceptions. Would it be possible to provide detailed error message in the wrapper exception or we always have to hunt for nested exceptions to get the real cause? But even then "Sample already exists" message is also somewhat confusing.

```
!ENTRY org.maven.ide.eclipse 4 0 2008-06-16 00:59:32.328
!MESSAGE Unable to create project from archetype [au.com.warpspeed.archetypes:basic-ear:1.0 -> null]
!STACK 0
org.apache.maven.archetype.exception.ArchetypeGenerationFailure: Failed to generate project from the old archetype
    at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.processOldArchetype(Unknown Source)
    at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(Unknown Source)
    at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(Unknown Source)
    at org.apache.maven.archetype.DefaultArchetype.generateProjectFromArchetype(Unknown Source)
    at org.maven.ide.eclipse.internal.project.ProjectConfigurationManager.createArchetypeProject(Unknown Source)
    at org.maven.ide.eclipse.wizards.MavenProjectWizard$4.runInWorkspace(Unknown Source)
    at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(Unknown Source)
    at org.eclipse.core.internal.jobs.Worker.run(Unknown Source)
Caused by: org.apache.maven.archetype.old.ArchetypeTemplateProcessingException: Sample already exists - please run from a clean directory
    at org.apache.maven.archetype.old.DefaultOldArchetype.createArchetype(Unknown Source)
    ... 8 more
```

**Comment by jira-importer** [comment]
**[Raphael Luta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphael)** commented

I upgraded a little the exception handling. Now the exception thrown from the old archetype code inherit from ArchetypeGenerationFailure therefore i need not to encapsulate them.
