### ISSUE TITLE
[ARCHETYPE-321] [regression] create-from-project results in FileNotFoundException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#697]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** opened **[ARCHETYPE-321](https://issues.apache.org/jira/browse/ARCHETYPE-321?redirect=false)** and commented

Using a clean project directory (mvn clean), I called:

```
mvn clean archetype:create-from-project -e
```

```
/target/generated-sources/archetype/src/main/resources/archetype-resources/pom.xml (No such file or directory)
        at org.apache.maven.archetype.mojos.CreateArchetypeFromProjectMojo.execute(CreateArchetypeFromProjectMojo.java:206)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:133)
```

I checked, and the directory target/generated-sources/archetype/src/main/resources/ does exist, but the archetype-resources directory is missing.

NOTE: When I run the same command with the previous version:

```
mvn clean org.apache.maven.plugins:maven-archetype-plugin:2.0-alpha-4:create-from-project -e
```

everything works fine.

---

**Affects:** 2.0-alpha-5

1 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

John,

Can you give a sample project causing such issue, please?
i don't understand your case

**Comment by jira-importer** [comment]
**[Matthias Friedrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mafr)** commented

Same problem here. I've created a minimal example project: http://users.mafr.de/~matthias/tmp/ARCHETYPE-321.tar.gz

This is the first problem I'm experiencing with archetype:create-from-project. Usually it works like a charm.

**Comment by jira-importer** [comment]
**[Graham Leggett](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=minfrin)** commented

FWIW, same problem here. 2.0-alpha-4 works, 2.0-alpha-5, 2.1 and 2.2 fail as per the reported exception.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
