### ISSUE TITLE
[ARCHETYPE-322] archetype:generate throws "Too many open files" error

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#709]
**[Przemek Dyk](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=przemek_dyk)** opened **[ARCHETYPE-322](https://issues.apache.org/jira/browse/ARCHETYPE-322?redirect=false)** and commented

mvn archetype:generate throws java.io.FileNotFoundException (Too many open files) when I try to generate application from archetype containing more files than system limit.
I've attached patch but I'm not sure if it's the best place to close files.

```
[ERROR] java.io.FileNotFoundException: /tmp/testartifact/src/main/webapp/css/test146.css (Too many open files)
org.apache.maven.archetype.exception.ArchetypeGenerationFailure: java.io.FileNotFoundException: /tmp/testartifact/src/main/webapp/css/test146.css (Too many open files)
        at org.apache.maven.archetype.generator.DefaultFilesetArchetypeGenerator.generateArchetype(DefaultFilesetArchetypeGenerator.java:215)
        at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.processFileSetArchetype(DefaultArchetypeGenerator.java:136)
        at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:106)
        at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:149)
        at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:209)
        at org.apache.maven.archetype.DefaultArchetypeManager.generateProjectFromArchetype(DefaultArchetypeManager.java:71)
        at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execute(CreateProjectFromArchetypeMojo.java:190)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

---

**Affects:** 2.0-alpha-5, 2.0

**Attachments:**
- [DefaultFilesetArchetypeGenerator.java.patch](https://issues.apache.org/jira/secure/attachment/12713849/DefaultFilesetArchetypeGenerator.java.patch) (_1.51 kB_)
- [run.sh](https://issues.apache.org/jira/secure/attachment/12713782/run.sh) (_339 bytes_)
- [test-archetype.zip](https://issues.apache.org/jira/secure/attachment/12713867/test-archetype.zip) (_530.80 kB_)

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

fixed in r983491
thank you
