### ISSUE TITLE
[ARCHETYPE-326] fail on mvn install with a archetype created from create-from-project command

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#712]
**[mid491](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mid491)** opened **[ARCHETYPE-326](https://issues.apache.org/jira/browse/ARCHETYPE-326?redirect=false)** and commented

Creatin archetype form my projects was working 2 days ago, now it is broken ^^

Try to create a project "foo" with "mvn archetype:generate",
choose 16 for exemple, and follow documentation steps :
- "mvn archetype:create-from-project"
- cd target/generated-sources/archetype/
- mvn install

stack trace :

```
[INFO] [archetype:integration-test {execution: default-integration-test}]
F:\dev\tmp\test\foo\target\generated-sources\archetype\target\test-classes\projects\basic\archetype.properties
[ERROR] Archetype fr.mycompany.foo:foo-archetype:1.0-SNAPSHOT is not configured
        Property archetype.goals is missing.
org.apache.maven.archetype.exception.ArchetypeNotConfigured: Archetype fr.mycompany.foo:foo-archetype:1.0-SNAPSHOT is not configured
        Property archetype.goals is missing.
        at org.apache.maven.archetype.generator.DefaultFilesetArchetypeGenerator.generateArchetype(DefaultFilesetArchetypeGenerator.java:127)
        at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.processFileSetArchetype(DefaultArchetypeGenerator.java:136)
        at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:106)
        at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:149)
        at org.apache.maven.archetype.mojos.IntegrationTestMojo.processIntegrationTest(IntegrationTestMojo.java:215)
        at org.apache.maven.archetype.mojos.IntegrationTestMojo.execute(IntegrationTestMojo.java:92)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Test basic failed
[Ljava.lang.StackTraceElement;@864e43
org.apache.maven.archetype.exception.ArchetypeNotConfigured: Archetype fr.mycompany.foo:foo-archetype:1.0-SNAPSHOT is not configured
        Property archetype.goals is missing.
```

---

**Affects:** 2.0-alpha-5

2 votes, 2 watchers

**Comment by jira-importer** [comment]
**[mid491](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mid491)** commented

this is on 2.0-alpha-6-SNAPSHOT version, work fine with 2.0-alpha-5

**Comment by jira-importer** [comment]
**[Kyle Kirkland](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kyleki)** commented

Just to provide additional confirmation of this issue, I'm experiencing the exact same thing with 2.0-alpha-6-SNAPSHOT.
