### ISSUE TITLE
[ARCHETYPE-352] archetype-commons ArchetyperRoundtripWithProxyTest unit test fail on OSX, but not on Windows nor Linux

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#723]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** opened **[ARCHETYPE-352](https://issues.apache.org/jira/browse/ARCHETYPE-352?redirect=false)** and commented

the failure happens only on a Mac:

```
Running org.apache.maven.archetype.test.ArchetyperRoundtripWithProxyTest
2010-11-27 15:21:09.018::INFO:  jetty-6.1.11
2010-11-27 15:21:09.025::INFO:  Extract jar:file:/Users/herve/projets/maven/trunks/archetype/archetype-common/target/proxy-webapp/cargocpc.war!/ to /tmp/Jetty_0_0_0_0_18882_cargocpc.war__cargocpc__wno9z4/webapp
2010-11-27 15:21:09.036::INFO:  NO JSP Support for /cargocpc, did not find org.apache.jasper.servlet.JspServlet
2010-11-27 15:21:10.059::INFO:  Started SelectChannelConnector@0.0.0.0:18882
2010-11-27 15:21:13.037::INFO:  Extract jar:file:/Users/herve/projets/maven/trunks/archetype/archetype-common/target/wars/archetype-proxy.war!/ to /tmp/Jetty_0_0_0_0_18882_archetype-proxy.war____o0siz0/webapp
2010-11-27 15:21:13.085::INFO:  NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2010-11-27 15:21:13.201:/:INFO:  Repository Servlet: Proxy Requested file = /dummy
2010-11-27 15:21:13.202:/:INFO:  Repository Servlet: Complete file path = /Users/herve/projets/maven/trunks/archetype/archetype-common/target/test-classes/repositories/central//dummy
2010-11-27 15:21:13.202:/:INFO:  Repository Servlet: Getting file
2010-11-27 15:21:13.202:/:INFO:  Repository Servlet: File sent
2010-11-27 15:21:13.213::INFO:  jetty-6.1.11
2010-11-27 15:21:13.220::INFO:  Extract jar:file:/Users/herve/projets/maven/trunks/archetype/archetype-common/target/repository-webapp/cargocpc.war!/ to /tmp/Jetty_0_0_0_0_18881_cargocpc.war__cargocpc__-40pz0h/webapp
2010-11-27 15:21:13.231::INFO:  NO JSP Support for /cargocpc, did not find org.apache.jasper.servlet.JspServlet
2010-11-27 15:21:13.243::INFO:  Started SelectChannelConnector@0.0.0.0:18881
2010-11-27 15:21:16.236::INFO:  Extract jar:file:/Users/herve/projets/maven/trunks/archetype/archetype-common/target/wars/archetype-repository.war!/ to /tmp/Jetty_0_0_0_0_18881_archetype-repository.war____nveesl/webapp
2010-11-27 15:21:16.289::INFO:  NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2010-11-27 15:21:16.401:/:INFO:  RepositoryServlet: Getting file
2010-11-27 15:21:16.401:/:INFO:  RepositoryServlet: Requested file = /repo/dummy
2010-11-27 15:21:16.403:/:INFO:  RepositoryServlet: Complete file path = /Users/herve/projets/maven/trunks/archetype/archetype-common/target/test-classes/repositories/central/dummy
2010-11-27 15:21:16.403:/:INFO:  RepositoryServlet: File sent
[INFO] Scanning for projects...
[WARNING] The POM for org.apache.maven.archetype:archetype-packaging:jar:2.1-SNAPSHOT is missing, no dependency information available
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.maven.test:test-project-2:1.0 (/Users/herve/projets/maven/trunks/archetype/archetype-common/target/test-classes/projects/roundtrip-2-project/target/generated-sources/archetype/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.maven.archetype:archetype-packaging:2.1-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.apache.maven.archetype:archetype-packaging:jar:2.1-SNAPSHOT -> [Help 2]
[ERROR]     Unknown packaging: maven-archetype @ line 8, column 14
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[ERROR] The desired archetype does not exist (org.apache.maven.test:test-project-2:1.0)
org.apache.maven.archetype.exception.UnknownArchetype: The desired archetype does not exist (org.apache.maven.test:test-project-2:1.0)                                                                               
        at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.getArchetypeFile(DefaultArchetypeGenerator.java:88)                                                                                        
        at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:207)                                                                                      
        at org.apache.maven.archetype.DefaultArchetypeManager.generateProjectFromArchetype(DefaultArchetypeManager.java:71)
        at org.apache.maven.archetype.test.ArchetyperRoundtripWithProxyTest.testArchetyper(ArchetyperRoundtripWithProxyTest.java:193)                                                                                
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                               
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)                                                                                                                             
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)                                                                                                                     
        at java.lang.reflect.Method.invoke(Method.java:585)                                                                                                                                                          
        at junit.framework.TestCase.runTest(TestCase.java:164)
        at junit.framework.TestCase.runBare(TestCase.java:130)                                                                                                                                                       
        at junit.framework.TestResult$1.protect(TestResult.java:106)                                                                                                                                                 
        at junit.framework.TestResult.runProtected(TestResult.java:124)                                                                                                                                              
        at junit.framework.TestResult.run(TestResult.java:109)                                                                                                                                                       
        at junit.framework.TestCase.run(TestCase.java:120)                                                                                                                                                           
        at junit.framework.TestSuite.runTest(TestSuite.java:230)                                                                                                                                                     
        at junit.framework.TestSuite.run(TestSuite.java:225)                                                                                                                                                         
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                               
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)                                                                                                                             
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)                                                                                                                     
        at java.lang.reflect.Method.invoke(Method.java:585)                                                                                                                                                          
        at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:213)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)                                                                                            
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)                                                                                                   
        at org.apache.maven.surefire.Surefire.run(Surefire.java:169)                                                                                                                                                 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)                                                                                                                             
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
        at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 90.075 sec <<< FAILURE!
```

but the warning ```
[WARNING] The POM for org.apache.maven.archetype:archetype-packaging:jar:2.1-SNAPSHOT is missing, no dependency information available

```
should happen on every platform since archetype-packaging install happens later in the reactor build:
```

[INFO] Reactor Summary:
[INFO]
[INFO] Maven Archetype ................................... SUCCESS [3.921s]
[INFO] Maven Archetype Testing ........................... SUCCESS [0.060s]
[INFO] Maven Archetype Webapp Proxy ...................... SUCCESS [3.306s]
[INFO] Maven Archetype Webapp Repository ................. SUCCESS [1.053s]
[INFO] Maven Archetype Models ............................ SUCCESS [0.057s]
[INFO] Maven Archetype Catalog Model ..................... SUCCESS [2.672s]
[INFO] Maven Archetype Descriptor Model .................. SUCCESS [1.673s]
[INFO] Maven Archetype Registry Model .................... SUCCESS [1.327s]
[INFO] Maven Archetype Common ............................ FAILURE [2:26.633s]
[INFO] Maven Archetype Plugin ............................ SKIPPED
[INFO] Maven Archetype Packaging ......................... SKIPPED

```

but on Linux and Windows, there is no failure
```

---

**Affects:** 2.0

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

note that it fails on Linux too if it has not previously been installed into the local repository

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
