### ISSUE TITLE
[ARCHETYPE-488] Goal integration-test of maven-archetype-plugin fails with 'Cannot run additions goals." in version 3.3.1

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#750]
**[Andreas Horst](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=andreas.horst)** opened **[ARCHETYPE-488](https://issues.apache.org/jira/browse/ARCHETYPE-488?redirect=false)** and commented

Running the goal 'integration-test' of the 'maven-archetype-plugin' fails with the following output:

```
[INFO] Invoking post-archetype-generation goals: verify
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.048 s
[INFO] Finished at: 2015-04-23T18:17:07+02:00
[INFO] Final Memory: 18M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.3:integration-test (default-integration-test) on project simple-archetype:
[ERROR] Archetype IT 'it' failed: Cannot run additions goals.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.3:integration-test (default-integration-test) on project simple-archetype:
Archetype IT 'it' failed: Cannot run additions goals.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException:
Archetype IT 'it' failed: Cannot run additions goals.
        at org.apache.maven.archetype.mojos.IntegrationTestMojo.execute(IntegrationTestMojo.java:258)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

This works fine in earlier versions (tested with Maven 3.2.5 and 3.2.3).

---

**Affects:** 2.4

**Issue Links:**
- [ARCHETYPE-507](https://issues.apache.org/jira/browse/ARCHETYPE-507) create-from-project fails on Windows
 (_**"is duplicated by"**_)
- [ARCHETYPE-516](https://issues.apache.org/jira/browse/ARCHETYPE-516) archetype:create-from-project fails on Windows since Maven-3.3.x
 (_**"is duplicated by"**_)
- [MSHARED-413](https://issues.apache.org/jira/browse/MSHARED-413) Invoker fails on Windows since Maven-3.3.x

5 votes, 14 watchers

**Comment by jira-importer** [comment]
**[Jörg Hohwiller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hohwille)** commented

I can confirm this problem and it seems a very general bug with archetype testing that I have tested for maven 3.3.1, 3.3.2 and 3.3.3 and all these 3.3.x versions are affected by the bug.
Therefore I have to stay with 3.2.x.

**Comment by jira-importer** [comment]
**[Kuzma Deretuke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ursa)** commented

Caught the same problem. The root cause is the difference in maven packaging:

* Maven 3.2: bin\mvn.bat
* Maven 3.3: bin\mvn.cmd

The problem disappears after creating a symlink mvn.bat => mvn.cmd:

```
> cd %MAVEN_HOME%\bin
> mklink mvn.bat mvn.cmd
```

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I would expect that upgrading `org.apache.maven.shared:maven-invoker` from 2.1.1 to 2.2 would fix this due to MSHARED-413. You don't need to wait for the next release, you can add this dependency to the plugin in your `pom.xml`

**Comment by jira-importer** [comment]
**[Alexis Resendiz Andrade](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=reaal)** commented

This problem still present in Maven 3.3.9

Is there a workaround for it? I tried with the suggestion in previous comment but is not working.

**Comment by jira-importer** [comment]
**[Jörg Hohwiller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hohwille)** commented

> Is there a workaround for it?

Yep. Just create a copy of "mvn.cmd" that you call "mvn.bat" in MAVEN_HOME/bin.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [e188f8fd091ade542fc2d31a4a2d7e05c631a6e9](https://git1-us-west.apache.org/repos/asf?p=maven-archetype.git;a=commit;h=e188f8fd)

**Comment by jira-importer** [comment]
**[Sébastien Gandon](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sgandon)** commented

Why is this bug closed, has it seems that the build failed upon this commit ?

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

First the integration build has not failed based on this commit (see the log file). apart from that you should have checked the following build (206) which was successful. BTW: Don't make discussions on JIRA issues. Better use the dev list for such things (Best is to remove the comment here and continue on dev list).

**Comment by jira-importer** [comment]
**[Sven Ro](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rottstock)** commented

[Alexis Resendiz Andrade](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=reaal): The upgrade of `org.apache.maven.shared:maven-invoker` is working for me if I add it as a dependency of maven-archetype-plugin - not as a separate plugin definition. So the _pom.xml_ should look as follows:

```xml
<plugin>
    <artifactId>maven-archetype-plugin</artifactId>
    <version>2.4</version>
    <dependencies>
        <dependency>
            <groupId>org.apache.maven.shared</groupId>
            <artifactId>maven-invoker</artifactId>
            <version>2.2</version>
        </dependency>
    </dependencies>
</plugin>
```

**Comment by jira-importer** [comment]
**[Manata Simanjuntak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER295261)** commented

Thank you `@Sven` Rottstock my problems was solve using you method(y)(y)
