### ISSUE TITLE
[ARCHETYPE-478] cannot run archetype:create-from-project when dependency on maven-ear-plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#751]
**[Bernard LUPIN](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lups)** opened **[ARCHETYPE-478](https://issues.apache.org/jira/browse/ARCHETYPE-478?redirect=false)** and commented

I'm migrating maven-archetype-plugin from 2.2 to 2.3.

I cannot create an archetype if my project has a dependency on maven-ear-plugin.
Using attached pom.xml and running mvn archetype:create-from-project gives me following error :
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.3:create-from-project (default-cli) on project myproj: null: MojoFailureException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.3:create-from-project (default-cli) on project myproj: null
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoFailureException
at org.apache.maven.archetype.mojos.CreateArchetypeFromProjectMojo.execute(CreateArchetypeFromProjectMojo.java:258)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)

I tried several versions of maven-ear-plugin, adding configuration or not, I always get this obscure error.

Everything works well with previous archetype plugin version 2.2.
And everything works well with archetype plugin version 2.3 without maven-ear-plugin.

Regards,
Bernard

---

**Affects:** 2.3

**Attachments:**
- [Debug screenshot showing call stack.png](https://issues.apache.org/jira/secure/attachment/12738554/Debug+screenshot+showing+call+stack.png) (_103.36 kB_)
- [Debug screenshot showing more call stack.png](https://issues.apache.org/jira/secure/attachment/12738555/Debug+screenshot+showing+more+call+stack.png) (_51.25 kB_)
- [myproj.zip](https://issues.apache.org/jira/secure/attachment/12713831/myproj.zip) (_764 bytes_)

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Pop Qvarnström](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=popq)** commented

FilesetArchetypeCreator:rewriteEARPluginReferences(...) seems to be the place where it blows up, while rewriting pluginManagement items. Ear plugin references are treated specially, and a configuration seems to be expected. If there is none (not uncommon in plugin management), there will be an NPE.

```
    private void rewriteEARPluginReferences( Plugin plugin, String rootArtifactId, String groupId )
    {
        Xpp3Dom configuration = (Xpp3Dom) plugin.getConfiguration();
HERE -->Xpp3Dom[] modules = configuration.getChild( "modules" ).getChildren();
        for ( int i = 0; i < modules.length; i++ )
```

Where it blows up:
!Debug screenshot showing call stack.png!

Source of the call:
!Debug screenshot showing more call stack.png!
