### ISSUE TITLE
[ARCHETYPE-570] Goal integration-test of maven-archetype-plugin fails "Archetype IT blueprint failed: Execution failure: exit code = 1"

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#812]
**[Gennady Chmelev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gvoxel)** opened **[ARCHETYPE-570](https://issues.apache.org/jira/browse/ARCHETYPE-570?redirect=false)** and commented

Installing old version Karaf 2.3.11 and get error  

```java
Apache Maven 3.0.4 (r1232337; 2012-01-17 11:44:56+0300)
Maven home: /mvn/apache-maven-3.0.4
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: ru_RU, platform encoding: MacCyrillic
OS name: "mac os x", version: "10.14.3", arch: "x86_64", family: "mac"

...
[INFO] Apache Karaf :: Tooling :: Maven2 Command Help plugin SUCCESS [2.751s]
[INFO] Apache Karaf :: Tooling :: Exam Testing Framework . SUCCESS [0.705s]
[INFO] Apache Karaf :: Tooling :: Exam Testing Framework :: Options SUCCESS [0.766s]
[INFO] Apache Karaf :: Tooling :: Exam Testing Framework :: Container SUCCESS [1.829s]
[INFO] Apache Karaf :: Archetypes ........................ SUCCESS [0.449s]
[INFO] Apache Karaf :: Archetypes :: Assembly Archetype .. FAILURE [26.041s]
[INFO] Apache Karaf :: Archetypes :: Blueprint Archetype . SKIPPED
[INFO] Apache Karaf :: Archetypes :: Bundle Archetype .... SKIPPED
[INFO] Apache Karaf :: Archetypes :: Command Archetype ... SKIPPED
[INFO] Apache Karaf :: Archetypes :: Feature Archetype ... SKIPPED
[INFO] Apache Karaf :: Archetypes :: Kar Archetype ....... SKIPPED
[INFO] Apache Karaf :: Integration Tests ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:58.002s
[INFO] Finished at: Mon Jul 08 16:01:11 MSD 2019
[INFO] Final Memory: 108M/403M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.2:integration-test (default-integration-test) on project karaf-blueprint-archetype:
[ERROR] Archetype IT 'blueprint' failed: Execution failure: exit code = 1
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.2:integration-test (default-integration-test) on project karaf-blueprint-archetype:
Archetype IT 'blueprint' failed: Execution failure: exit code = 1
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException:
Archetype IT 'blueprint' failed: Execution failure: exit code = 1
at org.apache.maven.archetype.mojos.IntegrationTestMojo.execute(IntegrationTestMojo.java:268)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
... 19 more
[ERROR]
```

 Please, helpful, what is the problem?

 

---

**Affects:** 2.2

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

Old issue without response ... If problem still exist should be tested with the latest version of all components
